defaults:
  - pipeline

sweep:
  command_args: >
    --config-name=aa
    inference.ckpt_path=
      /mnt/net/lab/pub/rfdiffusion2/model_weights/RFD_140.pt
    diffuser.T=50
    inference.deterministic=True
  benchmark_json: open_source_demo.json
  benchmarks: all
  num_per_condition: 1
  num_per_job: 1
  stop_step: sweep

outdir: /net/scratch/${oc.env:USER}/se3_diffusion/benchmarks/${now:%Y-%m-%d}_${now:%H-%M-%S}_demo
