defaults:
  - pipeline


sweep:
  command_args: >
    --config-name=aa
    inference.deterministic=True
    (
      inference.ckpt_path=
        REPO_ROOT/rf_diffusion/model_weights/RFD_140.pt
      ++transforms.configs.CenterPostTransform.center_type='all'
    )
    inference.contig_as_guidepost=True 
    diffuser.T=100
    inference.state_dict_to_load=model_state_dict
    inference.str_self_cond=False
    (
      inference.model_runner=NRBStyleSelfCond
    )
    ++idealization_metric_n_steps=50
    inference.idealize_sidechain_outputs=True
    ++diffuser.rots.sample_schedule=normed_exp
    ++diffuser.rots.exp_rate=10
    contigmap.intersperse='10-100'
    contigmap.reintersperse=True
    inference.guidepost_xyz_as_design_bb=[True]
  benchmark_json: mcsa_41.json
  benchmarks: all
  num_per_condition: 100
  num_per_job: 10
  slurm:
    p: gpu-bf
    gres: gpu:1

in_proc: False

mpnn:
  slurm:
    p: gpu
    gres: gpu:rtx2080:1

score:
  chunk: 200
  run: chai1
  chai1:
    slurm:
      p: gpu
      gres: gpu:a4000:1

outdir: /net/scratch/${oc.env:USER}/se3_diffusion/benchmarks/${now:%Y-%m-%d}_${now:%H-%M-%S}_enzyme_bench_n41

metrics:
  design_metrics:
    - backbone
    - rmsd_to_input
  sequence_metrics:
    - chai1_pocket_aligned_ligand
    - sidechain_symmetry_resolved

skip_steps:
- foldseek
- tm_align
