defaults:
  - enzyme_bench_n41


sweep:
  retries: 2
  command_args: >
    --config-name=aa
    inference.deterministic=True
    (
      inference.ckpt_path=
        REPO_ROOT/rf_diffusion/model_weights/RFD_140.pt
      ++transforms.configs.CenterPostTransform.center_type='all'
    )
    inference.contig_as_guidepost=True 
    diffuser.T=100
    inference.state_dict_to_load=model_state_dict
    inference.str_self_cond=False
    (
      inference.model_runner=NRBStyleSelfCond
    )
    ++idealization_metric_n_steps=50
    inference.idealize_sidechain_outputs=True
    ++diffuser.rots.sample_schedule=normed_exp
    ++diffuser.rots.exp_rate=10
    contigmap.intersperse='10-100'
    contigmap.reintersperse=True
    inference.guidepost_xyz_as_design_bb=[True]

    POST(
      (
        inference.partially_fixed_ligand=''
        inference.flexible_ligand=False
      )
    )

  slurm:
    p: gpu
    gres: gpu:rtx2080:1
outdir: /net/scratch/${oc.env:USER}/se3_diffusion/benchmarks/${now:%Y-%m-%d}_${now:%H-%M-%S}_enzyme_bench_n41_fixedligand
