defaults:
    - pipeline

sweep:
    num_per_condition: 200
    num_per_job: 20
    benchmark_json: bench_enzymes.json

score:
  run: af2

mpnn:
  num_seq_per_target: 8

in_proc: False
start_step: sweep
