defaults:
  - demo

in_proc: 1

sweep:
  command_args: >
    --config-name=aa
    inference.ckpt_path=
      /net/scratch/ahern/se3_diffusion/training/fm_tip_resume_24/fm_tip_resume_242023-12-03_14:20:34.490797/rank_0/models/RFD_44.pt
    diffuser.T=5
    inference.deterministic=True
    inference.ckpt_path=REPO_ROOT/rf_diffusion/model_weights/RFD_140.pt
    inference.write_trajectory=True
  benchmarks: extra_mini_retroaldolase
  benchmark_json: pipeline_test.json

mpnn:
  num_seq_per_target: 2
  preprocessing_slurm:
    in_proc: ${in_proc}
  omit_AA: ACDEFGIKLMNPQRSTVWYX

metrics:
  sequence_metrics:
    - sidechain_symmetry_resolved

outdir: /net/scratch/${oc.env:USER}/se3_diffusion/benchmarks/${now:%Y-%m-%d}_${now:%H-%M-%S}_pipeline_test