defaults:
  - sweep_hyperparam@sweep
  - cluster_pipeline_outputs@cluster
  - chunkify_foldseek_pdb@foldseek
  - mpnn_designs_v2@mpnn
  - score_designs@score
  - add_metrics@metrics

outdir: ${hydra:runtime.cwd}  # The dir the python script was called from
start_step: sweep
stop_step: end
skip_steps: [foldseek]
use_ligand: True
slurm_submit: True
in_proc: False
inpaint: False
af2_unmpnned: False
graft: False

sweep:
  command_args: --config-name=aa inference.ckpt_path=/net/scratch/ahern/se3_diffusion/training/from_scratch_4_resume_ep16/train_session2023-06-29_1688072531.6048305/models/RFD_30.pt
  out: ${outdir}/run
  slurm:
    in_proc: ${in_proc}
    submit: ${slurm_submit}

cluster:
  pipeline_outdir: ${outdir}
  slurm:
    in_proc: ${in_proc}
    submit: ${slurm_submit}

foldseek:
  pdb_dir: ${outdir}
  slurm:
    in_proc: ${in_proc}
    submit: ${slurm_submit}

mpnn:
  datadir: ${outdir}
  use_ligand: ${use_ligand}
  preprocessing_slurm:
    in_proc: ${in_proc}
    submit: ${slurm_submit}
  slurm:
    in_proc: ${in_proc}
    submit: ${slurm_submit}

score:
  trb_dir: ${outdir}
  slurm:
    in_proc: ${in_proc}
    submit: ${slurm_submit}

metrics:
  slurm:
    in_proc: ${in_proc}
    submit: ${slurm_submit}
  mpnn_dirs: ${mpnn.outdirs}

compile:
  metrics_chunk: -1

hydra:
  job_logging:
    root:
      level: WARN
