defaults:
  - pipeline

# This is a weird checkpoint but it's the only one that does center_type: is_diffused
#  Those inference.conditions shouldn't be required once we train a normal checkpoint
#  Also this checkpoint is not based on RFD140 but on structure prediction weights
sweep:
  command_args: >
    (
      command=(/usr/bin/apptainer run --nv -B /software -B /databases -B /net/databases /software/containers/RF_diffusion.sif -u /software/lab/diffusion/rf_diffusion/run_inference.py)
      --config-name=base
      *ppi_rf_bench_rfdiffusion.json
      inference.model_runner=NRBStyleSelfCond
      +inference.ckpt_override_path=/databases/lab/diffusion/models/hotspot_models/base_complex_finetuned_BFF_9.pt
      (
        denoiser.noise_scale_ca=0
        denoiser.noise_scale_frame=0
      )
      potentials.guide_scale=0
      inference.final_step=1
      ++inference.ligand=''
    )|(
      --config-name=aa_ppi_ideal
      *ppi_rf_bench.json
      inference.ckpt_path=
        /net/scratch/bcov/sc/design/zhichun/attempt1/zhichun_diffusion/epochs/ppi_tip_masked_seq_ideal_dhub_pae_cendif/RFD_14.pt
      transforms.configs.CenterPostTransform.center_type=hotspot
      inference.str_self_cond=False
      ++idealization_metric_n_steps=50
      +inference.conditions.per_res_plddt_pae_int_cond={}
      +inference.conditions.target_hbond_satisfaction_cond={}
    )
    inference.deterministic=True
    diffuser.T=200
  benchmark_json: null
  benchmarks: null
  num_per_condition: 100
  num_per_job: 20

mpnn:
  num_seq_per_target: 8

start_step: sweep
stop_step: end

score:
  chunk: 400
  run: af2_initial_guess

metrics:
  sequence_metrics:
    - default
    - af2_initial_guess_metrics


#outdir: /net/scratch/bcov/se3_diffusion/benchmarks/2024-12-10_22-12-28_ppi_v1
outdir: /net/scratch/${oc.env:USER}/se3_diffusion/benchmarks/${now:%Y-%m-%d}_${now:%H-%M-%S}_ppi_comparison