defaults:
  - pipeline

sweep:
  benchmark_json: training_benchmarks_ORI.json
  benchmarks: all
  num_per_condition: 10
  num_per_job: 10

metrics:
  design_metrics:
    - guidepost
    - backbone
    - sidechain