eval_params:
  checkpoint_path: "/home/dimaio/RF2-allatom-ref/models/rf2_48layer_ft_cull.pt"

experiment:
  output_dir: output_48layer_ft_cull

loader_params: 
  maxseq: 2048
  maxlat: 256
  crop: 1500
  p_msa_mask: 0.0
  maxcycle: 10

model: 
  embedding:
    rf2aa:
      params: 
        p_drop: 0.15
        templ_p_drop: 0.25
  blocks:
    RF2aa_full:
      num_blocks: 4
      params:
        p_drop_row: 0.25
        p_drop_pair: 0.25
        p_drop_layer: 0.0
        p_drop_outer_product: 0.0
        sc_pred_p_drop: 0.0
    RF2aa:
      num_blocks: 48
      params:
        p_drop_row: 0.25
        p_drop_pair: 0.25
        p_drop_layer: 0.0
        p_drop_outer_product: 0.0
        sc_pred_p_drop: 0.0

  refinement:
    local_adaptor:
      params:
        sc_pred_p_drop: 0.0
