defaults:
  - _self_
  - base
  - model: rf2aa_composed

experiment:
  name: rf2a-fd4-20240116
  trainer: "composed"

model:
  blocks:
    RF2aa_full: 
      num_blocks: 1
    RF2aa: 
      num_blocks: 1
  refinement:
    local:
      params:
        num_iterations: 4
        d_rbf: 64
        n_se3_layers: 2
        n_se3_channels: 32
        n_se3_degrees: 2
        n_se3_head: 4
        n_div: 4
        l0_in_features: 64
        l0_out_features: 64
        l1_in_features: 6
        l1_out_features: 2
        n_se3_edge_features: 64
        top_k: 64
        sc_pred_d_hidden: 128
        sc_pred_p_drop: 0.15
        residual_state: False
        compute_gradients: False
   
dataset_params:
  fraction_sm_compl: 1
  n_train: 25600

training_params:
  resume_train: False

loader_params:
  maxcycle: 1
  dataloader_kwargs:
    num_workers: 0
