defaults:
  - base
  - legacy_model_param: paper_model
  - loader_params: default
  - ddp_params: default

experiment:
  name: frank_model-10rec
  output_dir: null

loader_params: 
  maxlat: 256
  crop: 800
  maxcycle: 10
  nres_atomize_min: 3
  nres_atomize_max: 5
  dataloader_kwargs:
    num_workers: 0

ddp_params:
  port: 12375