defaults:
  - base 
  - model: untied_p2p
  - dataset_params: dataset_params_no_distillation
  - training_params: default_amp

experiment:
  name: rf2aa-reproduction
  trainer: "composed"

chem_params:
  use_lj_params_for_atoms: True
  use_phospate_frames_for_NA: False
