w_dist: 1.0
w_str: 10.0
w_inter_fape: 0.0
w_lig_fape: 0.0
w_lddt: 0.1
w_aa: 3.0
w_bond: 0.0
w_bind: 0.0
binder_loss_label_smoothing: 0.0
w_clash: 0.0
w_atom_bond: 0.0
w_skip_bond: 0.0
w_rigid: 0.0
w_hb: 0.0
w_pae: 0.1
w_pde: 0.0
lj_lin: 0.75