min_metal_contacts: 3
min_metal_contact_dist: 2.6
ligands_to_remove:
  -  10
  - 144
  - 15P
  - 1KA
  - 1PE
  - 2F2
  - 2PE
  - 74C
  - 7PE
  - 9JE
  - AAE
  - ACE
  - ACN
  - ACT
  - ACY
  - BCN
  - BCT
  - BEF
  - BF2
  - BF4
  - BME
  - BO3
  - BRJ
  - BU1
  - BU2
  - BU3
  - BU4
  - BUA
  - CAC
  - CAD
  - CCN
  - CHT
  - CNR
  - CO3
  - CO3
  - CXS
  - D10
  - D1D
  - DIO
  - DMF
  - DMS
  - DXE
  - DYD
  - EDO
  - EEE
  - EMC
  - EOH
  - EPE
  - ETA
  - ETF
  - FJO
  - FMT
  - FW5
  - GAI
  - GOL
  - GXT
  - HED
  - HEZ
  - HG2
  - I3M
  - IMD
  - IPA
  - IPH
  - LDA
  - MES
  - MMC
  - MOH
  - MPD
  - MRD
  - MXE
  - MYR
  - N  
  - NEH
  - NH2
  - NH3
  - NH4
  - NHE
  - NO3
  - NZ5
  - O4B
  - OLA
  - OLC
  - P3C
  - P6G
  - PC4
  - PDO
  - PE3
  - PE4
  - PEG
  - PG0
  - PG4
  - PGE
  - PGO
  - PGR
  - PLL
  - PLM
  - POL
  - SEY
  - SO3
  - SO4
  - SPD
  - SPM
  - STE
  - TBU
  - TME
  - TMO
  - TRS
  - UNK
  - UNL
  - UNX
  - UPL
  - URE
  - VO4
  - WO4
  - ZPT
  - 2HP
  - 2PO
  - MLA
  - MLI
  - PO3
  - PO4
  - POP
  - TAR
  - CL
  - F
  - BR
  - IOD
  - SGM
  - P4G
