global_params:
    d_msa: 256
    d_msa_full: 64
    d_pair: 192
    d_state: 64

embedding:
  rf2aa:
    params: 
      p_drop: 0.15
      d_templ: 64
      n_head_templ: 4
      d_hidden_templ: 64
      templ_p_drop: 0.25
      additional_dt1d: 0
      recycling_type: "msa_pair"
      use_same_chain: False
blocks:
  RF2aa_full:
    num_blocks: 4
    params:
      d_rbf: 64
      p_drop_row: 0.25
      p_drop_pair: 0.25
      p_drop_layer: 0.0
      msa_transition_drop: 0.0
      outer_product_channels: 16 
      p_drop_outer_product: 0.0
      n_pair_head: 6
      n_pair_channels: 32
      n_msa_head: 8
      n_msa_channels: 8
      structure_bias_gate_channels: 16
      structure_bias_channels: 64
      n_se3_layers: 1
      n_se3_channels: 32
      n_se3_degrees: 2
      n_se3_head: 4
      n_div: 4
      l0_in_features: 64
      l0_out_features: 64
      l1_in_features: 6
      l1_out_features: 2
      n_se3_edge_features: 64
      sc_pred_d_hidden: 128
      sc_pred_p_drop: 0.0
      residual_state: False
      norm_msa_row: False
      use_flash_attn: False
      bias_in_attn_norm: True
      compute_gradients: False
  RF2aa:
    num_blocks: 32
    params:
      d_rbf: 64
      p_drop_row: 0.25
      p_drop_pair: 0.25
      p_drop_layer: 0.0
      msa_transition_drop: 0.0
      outer_product_channels: 16 
      p_drop_outer_product: 0.0
      n_pair_head: 6
      n_pair_channels: 32
      n_msa_head: 8
      n_msa_channels: 32
      structure_bias_gate_channels: 16
      structure_bias_channels: 64
      n_se3_layers: 1
      n_se3_channels: 32
      n_se3_degrees: 2
      n_se3_head: 4
      n_div: 4
      l0_in_features: 64
      l0_out_features: 64
      l1_in_features: 6
      l1_out_features: 2
      n_se3_edge_features: 64
      sc_pred_d_hidden: 128
      sc_pred_p_drop: 0.0
      residual_state: False
      norm_msa_row: False
      use_flash_attn: False
      bias_in_attn_norm: True
      compute_gradients: False
auxiliary_predictors:
  c6d:
    n_feat: 192
    input_feature: "pair"
  mlm:
    n_feat: 256
    input_feature: "msa"
  pae:
    n_feat: 192
    input_feature: "pair"
  plddt: 
    n_feat: 64
    input_feature: "state"

