n_train: 24000
validate_every_n_epochs: 1
fraction_pdb: 0.3
fraction_fb: 0.0
fraction_compl: 0.1
fraction_neg_compl: 0
fraction_na_compl: 0.1
fraction_neg_na_compl: 0
fraction_distil_tf: 0.0
fraction_tf: 0
fraction_neg_tf: 0
fraction_rna: 0.03
fraction_dna: 0.02
fraction_sm_compl: 0.15
fraction_metal_compl: 0.04
fraction_sm_compl_multi: 0.03
fraction_sm_compl_covale: 0.03
fraction_sm: 0.0
fraction_atomize_pdb: 0.06
fraction_atomize_complex: 0.06
fraction_sm_compl_asmb: 0.08
n_valid_pdb: 256
n_valid_compl: 256
n_valid_rna: 256
n_valid_dna: 256
n_valid_sm_compl: 256
n_valid_sm_compl_strict: 256
