n_train: 24000
validate_every_n_epochs: 1
fraction_pdb: 0.12
fraction_fb: 0.36
fraction_compl: 0.055
fraction_neg_compl: 0
fraction_na_compl: 0.055
fraction_neg_na_compl: 0
fraction_distil_tf: 0.055 
fraction_tf: 0
fraction_neg_tf: 0 
fraction_rna: 0.02
fraction_dna: 0.005 
fraction_sm_compl: 0.11 
fraction_metal_compl: 0.03
fraction_sm_compl_multi: 0.025
fraction_sm_compl_covale: 0.025
fraction_sm: 0.0
fraction_atomize_pdb: 0.0425
fraction_atomize_complex: 0.0425
fraction_sm_compl_asmb: 0.055
n_valid_pdb: 256
n_valid_homo: 0
n_valid_dslf: 0 
n_valid_compl: 256
n_valid_neg_compl: 0 
n_valid_na_compl: 0
n_valid_neg_na_compl: 0 
n_valid_distil_tf: 0 
n_valid_tf: 0 
n_valid_neg_tf: 0 
n_valid_rna: 256
n_valid_dna: 256
n_valid_sm_compl: 256
n_valid_metal_compl: 0 
n_valid_sm_compl_multi: 0
n_valid_sm_compl_covale: 0 
n_valid_sm_compl_strict: 256
n_valid_sm: 0 
n_valid_atomize_pdb: 0 
n_valid_atomize_complex: 0 
n_valid_sm_compl_asmb: 0
p_homo_cut: 0
p_short_crop: 0 
p_dslf_crop: 0 
dslf_fb_upsample: 1
