defaults:
  - debug

inference:
  output_prefix: debug/aa_small
  model_runner: NRBStyleSelfCond
  input_pdb: 'benchmark/input/gaa.pdb'
  guidepost_xyz_as_design: True
  guidepost_xyz_as_design_bb: [True]
  contig_as_guidepost: False
  str_self_cond: 1
  ckpt_path: /net/databases/lab/aa-diffusion/models/RFD_45.pt

diffuser:
  center_noise_sample: true # Set the center of the noise sample 0,0,0

dataloader:
  P_IS_GUIDEPOST_EXAMPLE: 0.5

contigmap:
  contigs: ['10,A518-518,1']
