# Base inference Configuration.
defaults:
  - base

guidepost_bonds: True

inference:
  align_motif: False
  str_self_cond: True
  state_dict_to_use: model_state_dict
  deterministic: False
  ckpt_path: /net/scratch/ahern/se3_diffusion/training/fm_tip_resume_24/fm_tip_resume_242023-12-03_14:20:34.490797/rank_0/models/RFD_44.pt

diffuser:
  trans:
    sample_schedule: linear
    exp_rate: 1
