defaults:
  - base

benchmark:
  pipeline_yaml: training_benchmarks.yaml
ckpt_load_path: null
dataloader:
  DATASETS: pdb_aa,compl,sm_complex,sm_compl_covale,metal_compl,sm_compl_asmb,sm_compl_multi
  DATASET_PROB:
  - 0.4
  - 0.2
  - 0.15
  - 0.1
  - 0.05
  - 0.05
  - 0.05
  DIFF_MASK_PROBS:
    get_atomized_islands: 0.0
    get_closest_tip_atoms: 0.0
    get_closest_tip_atoms_partial_ligand: 0.0
    get_diffusion_mask_islands: 0.05
    get_diffusion_mask_islands_free_ligand: 0.05
    get_diffusion_mask_islands_partial_ligand: 0.05
    get_entirely_atomized: 0.0
    get_tip_mask: 0.125
    get_tip_mask_unconditional_free_ligand: 0.25
    get_tip_mask_unconditional_partial_ligand: 0.125
    get_unconditional_diffusion_mask: 0.075
    get_unconditional_diffusion_mask_free_ligand: 0.2
    get_unconditional_diffusion_mask_partial_ligand: 0.075
  P_IS_GUIDEPOST_EXAMPLE: 0.5
  USE_GUIDE_POSTS: false
diffuser:
  min_t: 0.01
  rots:
    exp_rate: 10
    sample_schedule: exp
    train_schedule: linear
  sampling:
    num_timesteps: 100
  so3:
    use_cached_score: true
  t_distribution: uniform_t001
  time_type: continuous
  trans:
    sample_schedule: linear
    train_schedule: linear
  type: flow_matching
experiment:
  aux_loss_ti_pass: 0.25
  aux_loss_weight: 0
  bb_atom_loss_weight: 0
  dist_mat_loss_weight: 0
  fm_rotation_loss_weight: 1.0
  fm_translation_loss_weight: 2.0
  normalize_trans_x0: true
  normalize_trans_x0_max_scaling: 50
  rot_loss_weight: 0
  trans_loss_weight: 0
  trans_x0_threshold: 0
extra_tXd:
- radius_of_gyration_v2
- relative_sasa_v2
- sinusoidal_timestep_embedding
extra_tXd_params:
  radius_of_gyration_v2:
    high: 100
    low: 10
    n_bins: 9
  relative_sasa_v2:
    high: 0.2
    low: 0
    n_bins: 3
  sinusoidal_timestep_embedding:
    embedding_dim: 20
    max_positions: 10000
fm:
  t_normalize_clip: 0.9
  trans_scale: 0.1
master_port: 12300
metrics:
- rigid_loss
- true_bond_lengths
- displacement_permutations
- rotations
- rotations_input
pseudobatch: 24
rf:
  model:
    d_t1d: 114
rundir: /net/scratch/${oc.env:USER}/se3_diffusion/training/flow_matching
scheduler:
  n_warmup_steps: 500
wandb_prefix: fm
