# Example yaml for training with ss/adj. Goes well with aa_ss_adj
defaults:
  - fm

rundir: /net/scratch/bcov/train_test
wandb_prefix: 'fm_tip_ss_adj'

ckpt_load_path: rf2a_25c_reshaped_t1d-119_t2d-72.pt

# Reshape an old weights file to make ^^ that
#ckpt_load_path: /home/bcov/sc/flow/binder_dev/rf_diffusion/models/rf2a_25c_414_t1d-114.pt
#reshape:
#    output_path: rf2a_25c_reshaped_t1d-119_t2d-72.pt


upstream_training_transforms:
  names:
    - GenerateMasks
    - PopMask
    - GenerateSSADJTrainingTransform
  configs:
    GenerateMasks: {}
    PopMask: {}
    GenerateSSADJTrainingTransform:
      p_is_ss_example: 0.2
      p_is_adj_example: 0.2
      ss_min_mask: 0.0
      ss_max_mask: 1.0
      adj_min_mask: 0.0
      adj_max_mask: 1.0
      p_any_strand_pairs: 0.2
      adj_strand_pair_min_mask: 0.0
      adj_strand_pair_max_mask: 1.0

transforms:
  names:
    - Center
    - AddConditionalInputs
    - ExpandConditionsDict

dataloader:
  P_IS_GUIDEPOST_EXAMPLE: 0.5
  DATAPKL_AA: aa_dataset_256.pkl
  DATASETS: pdb_aa,compl,sm_complex,sm_compl_covale,metal_compl,sm_compl_asmb,sm_compl_multi
  DATASET_PROB:
  - 0.4
  - 0.2
  - 0.15
  - 0.1
  - 0.05
  - 0.05
  - 0.05
  DIFF_MASK_PROBS:
    get_unconditional_diffusion_mask_free_ligand: 0.2
    get_unconditional_diffusion_mask: 0.075
    get_unconditional_diffusion_mask_partial_ligand: 0.075
    get_diffusion_mask_islands_free_ligand: 0.05
    get_diffusion_mask_islands: 0.05
    get_diffusion_mask_islands_partial_ligand: 0.05
    get_tip_mask: 0.125
    get_tip_mask_unconditional_free_ligand: 0.25
    get_tip_mask_unconditional_partial_ligand: 0.125

    get_closest_tip_atoms: 0.0
    get_closest_tip_atoms_partial_ligand: 0.0
    get_atomized_islands: 0.0
    get_entirely_atomized: 0.0

metrics:
  - rigid_loss
  - true_bond_lengths
  - displacement_permutations
  # - VarianceNormalizedPredTransMSE
  # - VarianceNormalizedInputTransMSE
  - rotations
  - rotations_input

diffuser:
  t_distribution: uniform_t001
  preserve_motif_sidechains: false

benchmark:
  pipeline_yaml: 'training_benchmarks.yaml'


extra_tXd:
  - radius_of_gyration_v2
  - relative_sasa_v2
  - sinusoidal_timestep_embedding
  - ss_adj_cond

extra_tXd_params:
  ss_adj_cond: {}

rf:
  model:
    use_chiral_l1: True
    use_lj_l1: True
    use_atom_frames: True
    use_same_chain: True
    recycling_type: all
    enable_same_chain: True
    refiner_topk: 128
    d_t1d: 119  # 114 + N_SS(5)
    d_t2d: 72   # 68 + N_ADJ(4)

show_dataset:
    show: True
    show_ss_cond: True # Show the secondary structure conditioning that has been applied
    ss_t1d_offset: -5 # Offset into t1d for the first (SS_HELIX) of the ss conditioning channels. Supports negative indexing
    show_adj_strand_pairs: True #  # Show secondary structural elements involved in strand pairing (ADJ_STRAND_PAIR)
    adj_t2d_offset: -4 # Offset into t2d for the first (ADJ_FAR) of the adj conditioning channels. Supports negative indexing
