# The base yaml for diffusing structures composed of multiple polymer/molecule classes
defaults:
  - fm

ckpt_load_path: /net/scratch/afavor/RFD_training/models/rf2a_25c_414_t1d-114.pt
# ckpt_load_path: /home/ahern/projects/aa_diffusion_data/models/rf2a_25c_414_t1d-114.pt

prob_self_cond: 0.0
seq_self_cond: False
inference:
  str_self_cond: false
  contig_as_guidepost: true

n_write_pdb: 30
saves_per_epoch: 5
rundir: /net/scratch/afavor/RFD_training/fm/multi_polymer

wandb_prefix: multi_polymer_run_01
wandb_project: multi_polymer_flow
wandb_dir: /scratch/afavor

upstream_training_transforms:
  names:
    - GenerateMasks
    - PopMask
  configs:
    GenerateMasks: {}
    PopMask: {}

transforms:
  names:
  - PopMask
  - Center
  - AddConditionalInputs
  - ExpandConditionsDict
  - RejectOutOfMemoryHazards
  configs:
    PopMask: {}
    Center: {}
    AddConditionalInputs:
      p_is_guidepost_example: 0.5
      guidepost_bonds: true
    ExpandConditionsDict: {}
    RejectOutOfMemoryHazards:
      max_size: 364

diffuser:
  t_distribution: uniform_t001
  preserve_motif_sidechains: false

dataloader:
  CROP: 256
  use_phospate_frames_for_NA: false
  P_IS_GUIDEPOST_EXAMPLE: 0.0
  DATAPKL_AA: multi_polymer_dataset_256.pkl
  DATASETS: pdb_aa,compl,sm_complex,metal_compl,na_compl,rna
  DATASET_PROB:
  - 0.14
  - 0.14
  - 0.02
  - 0.02
  - 0.34
  - 0.34
  DIFF_MASK_PROBS:
    get_diffusion_mask_simple: 0.25
    get_diffusion_mask_islands: 0.35
    get_diffusion_mask_islands_partial_ligand: 0.1
    get_unconditional_diffusion_mask: 0.2
    get_unconditional_diffusion_mask_free_ligand: 0.125
    get_unconditional_diffusion_mask_partial_ligand: 0.05
    get_closest_tip_atoms: 0.0
    get_closest_tip_atoms_partial_ligand: 0.0
    get_atomized_islands: 0.0
    get_entirely_atomized: 0.0


rf:
  model:
    use_chiral_l1: True
    use_lj_l1: True
    use_atom_frames: True
    use_same_chain: True
    recycling_type: all
    enable_same_chain: True
    refiner_topk: 128
    d_t1d: 114 # 114
    d_t2d: 68 # 68

extra_tXd:
  - radius_of_gyration_v2
  - relative_sasa_v2
  - sinusoidal_timestep_embedding

extra_tXd_params:
  radius_of_gyration_v2:
    prob: 0.0
  relative_sasa_v2:
    prob: 0.0


benchmark: False

experiment:
  trans_score_loss_weight: 0
  trans_x0_loss_weight: 0
  rot_score_loss_weight: 0
  bb_atom_loss_weight: 0
  dist_mat_loss_weight: 0
  c6d_dist_loss_weight: 0.001
  c6d_phi_loss_weight: 0.001
  c6d_theta_loss_weight: 0.001
  c6d_omega_loss_weight: 0.001
  fm_translation_loss_weight: 2.0
  fm_rotation_loss_weight: 1.0
  fm_bb_atom_loss_weight: 0
  fm_dist_mat_loss_weight: 0.01
  i_fm_translation_loss_weight: 0.0
  i_fm_rotation_loss_weight: 0.0
  fa_disp_loss_weight: 1.0
