defaults:
  - RFD_36

guidepost_bonds: false

dataloader:
  CROP: 10
  USE_GUIDE_POSTS: false
  DATASETS: pdb_aa
  DATASET_PROB: [1.0]
  DIFF_MASK_PROBS:
    atomize_all_res: 1.0
    get_closest_tip_atoms: 0.0
    get_unconditional_diffusion_mask: 0.0
    get_diffusion_mask_islands: 0.0
    get_closest_tip_atoms_partial_ligand: 0.0
    get_diffusion_mask_islands_partial_ligand: 0.0
    get_unconditional_diffusion_mask_partial_ligand: 0.0
  DATAPKL_AA: /home/dtischer/code/rf_diffusion_train/rf_diffusion/aa_dataset_256.pkl

experiment:
  trans_loss_weight: 1.0
  rot_loss_weight: 1.0
  trans_x0_threshold: 1.0
  normalize_trans_x0: true
  bb_atom_loss_weight: 0.0
  bb_atom_loss_t_filter: 0.0
  dist_mat_loss_weight: 0.0
  dist_mat_loss_t_filter: 0.0
  aux_loss_weight: 0.0
  c6d_loss_weight: 0.0
  diffuse_everything: true

diffuser:
  t_cont_max: 0.025

metrics:
- VarianceNormalizedPredTransMSE
- VarianceNormalizedInputTransMSE

n_write_pdb: 10
lr: 0.005
resume: null
resume_scheduler: false