defaults:
  - RFD_36_experiments

diffuser:
  time_type: continuous

rf:
  model:
    d_t1d: 614
  ckpt_path: null

extra_tXd:
  - radius_of_gyration_v2
  - relative_sasa_v2
  - little_t_embedding

extra_tXd_params:
  radius_of_gyration_v2:
    low: 10
    high: 100
    n_bins: 9
  relative_sasa_v2:
    low: 0
    high: 0.2
    n_bins: 3
  little_t_embedding: 
    boundary_style: low_t_heavy
    T: ${diffuser.T}

reshape:
  output_path: /home/dtischer/code/rf_diffusion_train/rf_diffusion/RFD_36_cont_time.pt

ckpt_load_path: /net/scratch/dtischer/231010_all_atom/ops/RFD_36_cont_time.pt
